<?php

namespace Jaevi\HotelesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HabitacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HabitacionRepository extends EntityRepository
{
    public function todosOrdenadosPorHotel() {
        $em=$this->getEntityManager();
        $habitaciones=$em->createQuery("select h from JaeviHotelesBundle:Habitacion h order by h.hotel")->getResult();
        return $habitaciones;
    }
}
