<?php

namespace Jaevi\HotelesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HabitacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelRepository extends EntityRepository
{
    public function prueba() {
        $em=$this->getEntityManager();
        $hoteles=$em->createQuery("select h from JaeviHotelesBundle:Hotel h order by h.id")->getResult();
        return $hoteles;
    }
}
